### ISSUE TITLE
Project is not Working

### ISSUE THREAD

**Issue by dhamodharanvemula** [venkata-sreeram/Chronic-Kidney-Disease-Prediction#1]
hai venkat,i think your project is not working properly.so,you work on this and once again upload project that is working fine.

**Comment by venkata-sreeram** [comment]
Hi @dhamodharanvemula I've checked this project code and is working fine as usual. May be the python libraries listed here might got out dated. I'll re-upload the requirements.txt again

**Comment by Sudhakardevar** [comment]
Hi Venkata Sir,
I'm facing an issue where the project is not working because the libraries in the requirements.txt file are outdated. After entering the details and clicking the submit button, I receive the message "Please enter valid data." Could you pls help me to resolving this issue!!
